# Generated by Django 4.1.2 on 2022-10-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50)),
                ('userR', models.CharField(max_length=50)),
                ('profileName', models.CharField(max_length=50)),
                ('helpfulness', models.CharField(max_length=10)),
                ('score', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
    ]
